# Generated by Django 2.2.4 on 2019-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnonMessager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
