# Generated by Django 2.2.4 on 2019-09-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnonMessager', '0002_auto_20190922_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
