# Generated by Django 2.2.4 on 2019-09-24 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnonMessager', '0005_auto_20190922_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='message',
            name='userMessage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageForYou', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
